app:
  name: "test"
  version: "1.0.0"
  port: 80
database:
  host: 127.0.0.1
  port: 3306
  username: "root"
  password: "123456"
cache:
  cache_type: "redis"
  host: 127.0.0.1
  port: 6379
  timeout: 3600
cookie:
  expire: 604800
  path: "/"
  secure: false
  http_only: true
session:
  secret: "8621E77D22F0830A46B462E3F46ED917"
  expire: 604800
  session_name: "session_8621E"
view:
  temp_path: "public/template/**/*"
  static_path: "public/static"
  delim_begin: "{{"
  delim_end: "}}"